// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bouzzszmopkzvcoqkqqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvdXp6c3ptb3BrenZjb3FrcXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNDkyOTUsImV4cCI6MjA5MDYyNTI5NX0.uJkIbzdOIn2Ul4WOzeAVXEdTaA2GV6knI0HVgUSiBxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});